name: Batch/NewjoyNotification

on:
  schedule:
    # 7:00 (JST) に処理を実行する。
    - cron: "0 22 * * *"
  push:

jobs:
  run_batch_newjoy_notification:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/set-timezone-action@v1.1
        with:
          timezoneLinux: "Asia/Tokyo"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./batch/newjoy_notification
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot.py
        working-directory: ./batch/newjoy_notification
        env:
          TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          API_URL: https://api.uu-circles.com/api/circle/newjoy
        run: |
          python bot.py
