name: CreatePullrequest
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  build:
    name: CreatePullrequest
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
